# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: memory.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'memory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmemory.proto\x12\x0f\x66orge.memory.v1\"\x0f\n\rHealthRequest\"0\n\x0eHealthResponse\x12\r\n\x05ready\x18\x01 \x01(\x08\x12\x0f\n\x07version\x18\x02 \x01(\t\")\n\rRecallRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\t\n\x01k\x18\x02 \x01(\r\"a\n\x0bMemoryMatch\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05\x61gent\x18\x02 \x01(\t\x12\x15\n\rdecision_json\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\t\x12\r\n\x05score\x18\x05 \x01(\x01\"?\n\x0eRecallResponse\x12-\n\x07matches\x18\x01 \x03(\x0b\x32\x1c.forge.memory.v1.MemoryMatch\":\n\x0bListRequest\x12\x12\n\x05\x61gent\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\r\n\x05limit\x18\x02 \x01(\rB\x08\n\x06_agent\"}\n\rMemorySummary\x12\r\n\x05\x61gent\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\r\x12\x1c\n\x14latest_decision_json\x18\x03 \x01(\t\x12\x18\n\x10latest_timestamp\x18\x04 \x01(\t\x12\x16\n\x0etop_confidence\x18\x05 \x01(\x01\">\n\x0cListResponse\x12.\n\x06\x61gents\x18\x01 \x03(\x0b\x32\x1e.forge.memory.v1.MemorySummary2\xea\x01\n\rMemoryService\x12I\n\x06Health\x12\x1e.forge.memory.v1.HealthRequest\x1a\x1f.forge.memory.v1.HealthResponse\x12I\n\x06Recall\x12\x1e.forge.memory.v1.RecallRequest\x1a\x1f.forge.memory.v1.RecallResponse\x12\x43\n\x04List\x12\x1c.forge.memory.v1.ListRequest\x1a\x1d.forge.memory.v1.ListResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'memory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHREQUEST']._serialized_start=33
  _globals['_HEALTHREQUEST']._serialized_end=48
  _globals['_HEALTHRESPONSE']._serialized_start=50
  _globals['_HEALTHRESPONSE']._serialized_end=98
  _globals['_RECALLREQUEST']._serialized_start=100
  _globals['_RECALLREQUEST']._serialized_end=141
  _globals['_MEMORYMATCH']._serialized_start=143
  _globals['_MEMORYMATCH']._serialized_end=240
  _globals['_RECALLRESPONSE']._serialized_start=242
  _globals['_RECALLRESPONSE']._serialized_end=305
  _globals['_LISTREQUEST']._serialized_start=307
  _globals['_LISTREQUEST']._serialized_end=365
  _globals['_MEMORYSUMMARY']._serialized_start=367
  _globals['_MEMORYSUMMARY']._serialized_end=492
  _globals['_LISTRESPONSE']._serialized_start=494
  _globals['_LISTRESPONSE']._serialized_end=556
  _globals['_MEMORYSERVICE']._serialized_start=559
  _globals['_MEMORYSERVICE']._serialized_end=793
# @@protoc_insertion_point(module_scope)
